### ISSUE TITLE
firefox

### ISSUE THREAD

**Issue by N0VA-The-Git-User** [aguywhosaguy/thirtydollarcustomsounds#1]
Can you make a version for firefox pls?

**Comment by stupidratcreature1000** [comment]
its open source do it yourself

**Comment by MissingCake19** [comment]
> its open source do it yourself

heck you, not anyone can do it

**Comment by aguywhosaguy** [comment]
hey - saw your comment just now, sorry about the 9 month gap

i actually use firefox as my main browser. developing extensions for it sucks for the main reason that whenever you select a file, the extension closes and each work around i tried failed

i should've archived this repo a long time ago. it's not very good html or css, and the js isn't that great either. 
overall, i feel like someone with html and css skills could do this way better than i could.

**Comment by aguywhosaguy** [comment]
this extension has been replaced by the new [Thirty Dollar Extension](https://github.com/aguywhosaguy/thirtyDollarExtension), which includes firefox support. this issue will be closed, and this repo will be archived.
